/*
Package lacp is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema. The generated paths are
based on a compressed form of the schema.

This package was generated by /usr/local/google/home/gdennis/go/pkg/mod/github.com/openconfig/ygot@v0.25.2/genutil/names.go
using the following YANG input files:
  - models-yang/models/isis/open-traffic-generator-isis.yang
  - models-yang/models/types/open-traffic-generator-types.yang
  - models-yang/models/flow/open-traffic-generator-flow.yang
  - models-yang/models/discovery/open-traffic-generator-discovery.yang
  - models-yang/models/interface/open-traffic-generator-port.yang
  - models-yang/models/bgp/open-traffic-generator-bgp.yang
  - models-yang/models/lag/open-traffic-generator-lag.yang
  - models-yang/models/lacp/open-traffic-generator-lacp.yang

Imported modules were sourced from:
  - models-yang/models/...
*/
package lacp

import (
	"github.com/openconfig/ygot/ygot"
)

// LacpPath represents the /open-traffic-generator-lacp/lacp YANG schema element.
type LacpPath struct {
	*ygot.NodePath
}

// LacpPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp YANG schema element.
type LacpPathAny struct {
	*ygot.NodePath
}

// LagMemberAny (list): Each LAG member (port) is identified by an arbitrary string
// identifier.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lag-members/lag-member"
// Path from root: "/lacp/lag-members/lag-member"
// Name (wildcarded): string
func (n *LacpPath) LagMemberAny() *Lacp_LagMemberPathAny {
	return &Lacp_LagMemberPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lag-members", "lag-member"},
			map[string]interface{}{"name": "*"},
			n,
		),
	}
}

// LagMemberAny (list): Each LAG member (port) is identified by an arbitrary string
// identifier.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lag-members/lag-member"
// Path from root: "/lacp/lag-members/lag-member"
// Name (wildcarded): string
func (n *LacpPathAny) LagMemberAny() *Lacp_LagMemberPathAny {
	return &Lacp_LagMemberPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lag-members", "lag-member"},
			map[string]interface{}{"name": "*"},
			n,
		),
	}
}

// LagMember (list): Each LAG member (port) is identified by an arbitrary string
// identifier.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lag-members/lag-member"
// Path from root: "/lacp/lag-members/lag-member"
// Name: string
func (n *LacpPath) LagMember(Name string) *Lacp_LagMemberPath {
	return &Lacp_LagMemberPath{
		NodePath: ygot.NewNodePath(
			[]string{"lag-members", "lag-member"},
			map[string]interface{}{"name": Name},
			n,
		),
	}
}

// LagMember (list): Each LAG member (port) is identified by an arbitrary string
// identifier.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lag-members/lag-member"
// Path from root: "/lacp/lag-members/lag-member"
// Name: string
func (n *LacpPathAny) LagMember(Name string) *Lacp_LagMemberPathAny {
	return &Lacp_LagMemberPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lag-members", "lag-member"},
			map[string]interface{}{"name": Name},
			n,
		),
	}
}

// Lacp_LagMemberPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member YANG schema element.
type Lacp_LagMemberPath struct {
	*ygot.NodePath
}

// Lacp_LagMemberPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member YANG schema element.
type Lacp_LagMemberPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_ActivityPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/activity YANG schema element.
type Lacp_LagMember_ActivityPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_ActivityPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/activity YANG schema element.
type Lacp_LagMember_ActivityPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_AggregatablePath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/aggregatable YANG schema element.
type Lacp_LagMember_AggregatablePath struct {
	*ygot.NodePath
}

// Lacp_LagMember_AggregatablePathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/aggregatable YANG schema element.
type Lacp_LagMember_AggregatablePathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_CollectingPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/collecting YANG schema element.
type Lacp_LagMember_CollectingPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_CollectingPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/collecting YANG schema element.
type Lacp_LagMember_CollectingPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_DistributingPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/distributing YANG schema element.
type Lacp_LagMember_DistributingPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_DistributingPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/distributing YANG schema element.
type Lacp_LagMember_DistributingPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_NamePath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/name YANG schema element.
type Lacp_LagMember_NamePath struct {
	*ygot.NodePath
}

// Lacp_LagMember_NamePathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/name YANG schema element.
type Lacp_LagMember_NamePathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_OperKeyPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/oper-key YANG schema element.
type Lacp_LagMember_OperKeyPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_OperKeyPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/oper-key YANG schema element.
type Lacp_LagMember_OperKeyPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerIdPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-id YANG schema element.
type Lacp_LagMember_PartnerIdPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerIdPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-id YANG schema element.
type Lacp_LagMember_PartnerIdPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerKeyPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-key YANG schema element.
type Lacp_LagMember_PartnerKeyPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerKeyPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-key YANG schema element.
type Lacp_LagMember_PartnerKeyPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerPortNumPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-port-num YANG schema element.
type Lacp_LagMember_PartnerPortNumPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_PartnerPortNumPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/partner-port-num YANG schema element.
type Lacp_LagMember_PartnerPortNumPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_PortNumPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/port-num YANG schema element.
type Lacp_LagMember_PortNumPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_PortNumPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/port-num YANG schema element.
type Lacp_LagMember_PortNumPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_SynchronizationPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/synchronization YANG schema element.
type Lacp_LagMember_SynchronizationPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_SynchronizationPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/synchronization YANG schema element.
type Lacp_LagMember_SynchronizationPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_SystemIdPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/system-id YANG schema element.
type Lacp_LagMember_SystemIdPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_SystemIdPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/system-id YANG schema element.
type Lacp_LagMember_SystemIdPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_TimeoutPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/timeout YANG schema element.
type Lacp_LagMember_TimeoutPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_TimeoutPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/timeout YANG schema element.
type Lacp_LagMember_TimeoutPathAny struct {
	*ygot.NodePath
}

// Activity (leaf): Indicates participant is active or passive
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/activity"
// Path from root: "/lacp/lag-members/lag-member/state/activity"
func (n *Lacp_LagMemberPath) Activity() *Lacp_LagMember_ActivityPath {
	return &Lacp_LagMember_ActivityPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "activity"},
			map[string]interface{}{},
			n,
		),
	}
}

// Activity (leaf): Indicates participant is active or passive
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/activity"
// Path from root: "/lacp/lag-members/lag-member/state/activity"
func (n *Lacp_LagMemberPathAny) Activity() *Lacp_LagMember_ActivityPathAny {
	return &Lacp_LagMember_ActivityPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "activity"},
			map[string]interface{}{},
			n,
		),
	}
}

// Aggregatable (leaf): A true value indicates that the participant will allow
// the link to be used as part of the aggregate. A false
// value indicates the link should be used as an individual
// link
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/aggregatable"
// Path from root: "/lacp/lag-members/lag-member/state/aggregatable"
func (n *Lacp_LagMemberPath) Aggregatable() *Lacp_LagMember_AggregatablePath {
	return &Lacp_LagMember_AggregatablePath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "aggregatable"},
			map[string]interface{}{},
			n,
		),
	}
}

// Aggregatable (leaf): A true value indicates that the participant will allow
// the link to be used as part of the aggregate. A false
// value indicates the link should be used as an individual
// link
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/aggregatable"
// Path from root: "/lacp/lag-members/lag-member/state/aggregatable"
func (n *Lacp_LagMemberPathAny) Aggregatable() *Lacp_LagMember_AggregatablePathAny {
	return &Lacp_LagMember_AggregatablePathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "aggregatable"},
			map[string]interface{}{},
			n,
		),
	}
}

// Collecting (leaf): If true, the participant is collecting incoming frames
// on the link, otherwise false
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/collecting"
// Path from root: "/lacp/lag-members/lag-member/state/collecting"
func (n *Lacp_LagMemberPath) Collecting() *Lacp_LagMember_CollectingPath {
	return &Lacp_LagMember_CollectingPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "collecting"},
			map[string]interface{}{},
			n,
		),
	}
}

// Collecting (leaf): If true, the participant is collecting incoming frames
// on the link, otherwise false
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/collecting"
// Path from root: "/lacp/lag-members/lag-member/state/collecting"
func (n *Lacp_LagMemberPathAny) Collecting() *Lacp_LagMember_CollectingPathAny {
	return &Lacp_LagMember_CollectingPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "collecting"},
			map[string]interface{}{},
			n,
		),
	}
}

// Counters (container): Counters of an individual LACP peer.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/counters"
// Path from root: "/lacp/lag-members/lag-member/state/counters"
func (n *Lacp_LagMemberPath) Counters() *Lacp_LagMember_CountersPath {
	return &Lacp_LagMember_CountersPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "counters"},
			map[string]interface{}{},
			n,
		),
	}
}

// Counters (container): Counters of an individual LACP peer.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/counters"
// Path from root: "/lacp/lag-members/lag-member/state/counters"
func (n *Lacp_LagMemberPathAny) Counters() *Lacp_LagMember_CountersPathAny {
	return &Lacp_LagMember_CountersPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "counters"},
			map[string]interface{}{},
			n,
		),
	}
}

// Distributing (leaf): When true, the participant is distributing outgoing
// frames; when false, distribution is disabled
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/distributing"
// Path from root: "/lacp/lag-members/lag-member/state/distributing"
func (n *Lacp_LagMemberPath) Distributing() *Lacp_LagMember_DistributingPath {
	return &Lacp_LagMember_DistributingPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "distributing"},
			map[string]interface{}{},
			n,
		),
	}
}

// Distributing (leaf): When true, the participant is distributing outgoing
// frames; when false, distribution is disabled
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/distributing"
// Path from root: "/lacp/lag-members/lag-member/state/distributing"
func (n *Lacp_LagMemberPathAny) Distributing() *Lacp_LagMember_DistributingPathAny {
	return &Lacp_LagMember_DistributingPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "distributing"},
			map[string]interface{}{},
			n,
		),
	}
}

// Name (leaf): An arbitary name of the LACP peer determined by the ATE
// configuration.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/name"
// Path from root: "/lacp/lag-members/lag-member/state/name"
func (n *Lacp_LagMemberPath) Name() *Lacp_LagMember_NamePath {
	return &Lacp_LagMember_NamePath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "name"},
			map[string]interface{}{},
			n,
		),
	}
}

// Name (leaf): An arbitary name of the LACP peer determined by the ATE
// configuration.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/name"
// Path from root: "/lacp/lag-members/lag-member/state/name"
func (n *Lacp_LagMemberPathAny) Name() *Lacp_LagMember_NamePathAny {
	return &Lacp_LagMember_NamePathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "name"},
			map[string]interface{}{},
			n,
		),
	}
}

// OperKey (leaf): Current operational value of the key for the aggregate
// interface
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/oper-key"
// Path from root: "/lacp/lag-members/lag-member/state/oper-key"
func (n *Lacp_LagMemberPath) OperKey() *Lacp_LagMember_OperKeyPath {
	return &Lacp_LagMember_OperKeyPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "oper-key"},
			map[string]interface{}{},
			n,
		),
	}
}

// OperKey (leaf): Current operational value of the key for the aggregate
// interface
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/oper-key"
// Path from root: "/lacp/lag-members/lag-member/state/oper-key"
func (n *Lacp_LagMemberPathAny) OperKey() *Lacp_LagMember_OperKeyPathAny {
	return &Lacp_LagMember_OperKeyPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "oper-key"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerId (leaf): MAC address representing the protocol partner's interface
// system ID
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-id"
// Path from root: "/lacp/lag-members/lag-member/state/partner-id"
func (n *Lacp_LagMemberPath) PartnerId() *Lacp_LagMember_PartnerIdPath {
	return &Lacp_LagMember_PartnerIdPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-id"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerId (leaf): MAC address representing the protocol partner's interface
// system ID
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-id"
// Path from root: "/lacp/lag-members/lag-member/state/partner-id"
func (n *Lacp_LagMemberPathAny) PartnerId() *Lacp_LagMember_PartnerIdPathAny {
	return &Lacp_LagMember_PartnerIdPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-id"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerKey (leaf): Operational value of the protocol partner's key
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-key"
// Path from root: "/lacp/lag-members/lag-member/state/partner-key"
func (n *Lacp_LagMemberPath) PartnerKey() *Lacp_LagMember_PartnerKeyPath {
	return &Lacp_LagMember_PartnerKeyPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-key"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerKey (leaf): Operational value of the protocol partner's key
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-key"
// Path from root: "/lacp/lag-members/lag-member/state/partner-key"
func (n *Lacp_LagMemberPathAny) PartnerKey() *Lacp_LagMember_PartnerKeyPathAny {
	return &Lacp_LagMember_PartnerKeyPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-key"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerPortNum (leaf): Port number of the partner (remote) port for this member
// port
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-port-num"
// Path from root: "/lacp/lag-members/lag-member/state/partner-port-num"
func (n *Lacp_LagMemberPath) PartnerPortNum() *Lacp_LagMember_PartnerPortNumPath {
	return &Lacp_LagMember_PartnerPortNumPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-port-num"},
			map[string]interface{}{},
			n,
		),
	}
}

// PartnerPortNum (leaf): Port number of the partner (remote) port for this member
// port
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/partner-port-num"
// Path from root: "/lacp/lag-members/lag-member/state/partner-port-num"
func (n *Lacp_LagMemberPathAny) PartnerPortNum() *Lacp_LagMember_PartnerPortNumPathAny {
	return &Lacp_LagMember_PartnerPortNumPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "partner-port-num"},
			map[string]interface{}{},
			n,
		),
	}
}

// PortNum (leaf): Port number of the local (actor) aggregation member
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/port-num"
// Path from root: "/lacp/lag-members/lag-member/state/port-num"
func (n *Lacp_LagMemberPath) PortNum() *Lacp_LagMember_PortNumPath {
	return &Lacp_LagMember_PortNumPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "port-num"},
			map[string]interface{}{},
			n,
		),
	}
}

// PortNum (leaf): Port number of the local (actor) aggregation member
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/port-num"
// Path from root: "/lacp/lag-members/lag-member/state/port-num"
func (n *Lacp_LagMemberPathAny) PortNum() *Lacp_LagMember_PortNumPathAny {
	return &Lacp_LagMember_PortNumPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "port-num"},
			map[string]interface{}{},
			n,
		),
	}
}

// Synchronization (leaf): Indicates whether the participant is in-sync or
// out-of-sync
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/synchronization"
// Path from root: "/lacp/lag-members/lag-member/state/synchronization"
func (n *Lacp_LagMemberPath) Synchronization() *Lacp_LagMember_SynchronizationPath {
	return &Lacp_LagMember_SynchronizationPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "synchronization"},
			map[string]interface{}{},
			n,
		),
	}
}

// Synchronization (leaf): Indicates whether the participant is in-sync or
// out-of-sync
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/synchronization"
// Path from root: "/lacp/lag-members/lag-member/state/synchronization"
func (n *Lacp_LagMemberPathAny) Synchronization() *Lacp_LagMember_SynchronizationPathAny {
	return &Lacp_LagMember_SynchronizationPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "synchronization"},
			map[string]interface{}{},
			n,
		),
	}
}

// SystemId (leaf): MAC address that defines the local system ID for the
// aggregate interface
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/system-id"
// Path from root: "/lacp/lag-members/lag-member/state/system-id"
func (n *Lacp_LagMemberPath) SystemId() *Lacp_LagMember_SystemIdPath {
	return &Lacp_LagMember_SystemIdPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "system-id"},
			map[string]interface{}{},
			n,
		),
	}
}

// SystemId (leaf): MAC address that defines the local system ID for the
// aggregate interface
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/system-id"
// Path from root: "/lacp/lag-members/lag-member/state/system-id"
func (n *Lacp_LagMemberPathAny) SystemId() *Lacp_LagMember_SystemIdPathAny {
	return &Lacp_LagMember_SystemIdPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "system-id"},
			map[string]interface{}{},
			n,
		),
	}
}

// Timeout (leaf): The timeout type (short or long) used by the
// participant
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/timeout"
// Path from root: "/lacp/lag-members/lag-member/state/timeout"
func (n *Lacp_LagMemberPath) Timeout() *Lacp_LagMember_TimeoutPath {
	return &Lacp_LagMember_TimeoutPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "timeout"},
			map[string]interface{}{},
			n,
		),
	}
}

// Timeout (leaf): The timeout type (short or long) used by the
// participant
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "state/timeout"
// Path from root: "/lacp/lag-members/lag-member/state/timeout"
func (n *Lacp_LagMemberPathAny) Timeout() *Lacp_LagMember_TimeoutPathAny {
	return &Lacp_LagMember_TimeoutPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "timeout"},
			map[string]interface{}{},
			n,
		),
	}
}

// Lacp_LagMember_CountersPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters YANG schema element.
type Lacp_LagMember_CountersPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_CountersPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters YANG schema element.
type Lacp_LagMember_CountersPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpInPktsPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-in-pkts YANG schema element.
type Lacp_LagMember_Counters_LacpInPktsPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpInPktsPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-in-pkts YANG schema element.
type Lacp_LagMember_Counters_LacpInPktsPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpOutPktsPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-out-pkts YANG schema element.
type Lacp_LagMember_Counters_LacpOutPktsPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpOutPktsPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-out-pkts YANG schema element.
type Lacp_LagMember_Counters_LacpOutPktsPathAny struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpRxErrorsPath represents the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-rx-errors YANG schema element.
type Lacp_LagMember_Counters_LacpRxErrorsPath struct {
	*ygot.NodePath
}

// Lacp_LagMember_Counters_LacpRxErrorsPathAny represents the wildcard version of the /open-traffic-generator-lacp/lacp/lag-members/lag-member/state/counters/lacp-rx-errors YANG schema element.
type Lacp_LagMember_Counters_LacpRxErrorsPathAny struct {
	*ygot.NodePath
}

// LacpInPkts (leaf): The total number of LACPDUs received.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-in-pkts"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-in-pkts"
func (n *Lacp_LagMember_CountersPath) LacpInPkts() *Lacp_LagMember_Counters_LacpInPktsPath {
	return &Lacp_LagMember_Counters_LacpInPktsPath{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-in-pkts"},
			map[string]interface{}{},
			n,
		),
	}
}

// LacpInPkts (leaf): The total number of LACPDUs received.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-in-pkts"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-in-pkts"
func (n *Lacp_LagMember_CountersPathAny) LacpInPkts() *Lacp_LagMember_Counters_LacpInPktsPathAny {
	return &Lacp_LagMember_Counters_LacpInPktsPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-in-pkts"},
			map[string]interface{}{},
			n,
		),
	}
}

// LacpOutPkts (leaf): The total number of LACPDUs transmitted.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-out-pkts"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-out-pkts"
func (n *Lacp_LagMember_CountersPath) LacpOutPkts() *Lacp_LagMember_Counters_LacpOutPktsPath {
	return &Lacp_LagMember_Counters_LacpOutPktsPath{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-out-pkts"},
			map[string]interface{}{},
			n,
		),
	}
}

// LacpOutPkts (leaf): The total number of LACPDUs transmitted.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-out-pkts"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-out-pkts"
func (n *Lacp_LagMember_CountersPathAny) LacpOutPkts() *Lacp_LagMember_Counters_LacpOutPktsPathAny {
	return &Lacp_LagMember_Counters_LacpOutPktsPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-out-pkts"},
			map[string]interface{}{},
			n,
		),
	}
}

// LacpRxErrors (leaf): The total number of LACPDUs receive packet errors.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-rx-errors"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-rx-errors"
func (n *Lacp_LagMember_CountersPath) LacpRxErrors() *Lacp_LagMember_Counters_LacpRxErrorsPath {
	return &Lacp_LagMember_Counters_LacpRxErrorsPath{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-rx-errors"},
			map[string]interface{}{},
			n,
		),
	}
}

// LacpRxErrors (leaf): The total number of LACPDUs receive packet errors.
// ----------------------------------------
// Defining module: "open-traffic-generator-lacp"
// Instantiating module: "open-traffic-generator-lacp"
// Path from parent: "lacp-rx-errors"
// Path from root: "/lacp/lag-members/lag-member/state/counters/lacp-rx-errors"
func (n *Lacp_LagMember_CountersPathAny) LacpRxErrors() *Lacp_LagMember_Counters_LacpRxErrorsPathAny {
	return &Lacp_LagMember_Counters_LacpRxErrorsPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"lacp-rx-errors"},
			map[string]interface{}{},
			n,
		),
	}
}
