/*
Package lag is a generated package which contains definitions
of structs which generate gNMI paths for a YANG schema. The generated paths are
based on a compressed form of the schema.

This package was generated by /usr/local/google/home/alexmasi/go/pkg/mod/github.com/openconfig/ygot@v0.25.2/genutil/names.go
using the following YANG input files:
  - models-yang/models/isis/open-traffic-generator-isis.yang
  - models-yang/models/types/open-traffic-generator-types.yang
  - models-yang/models/flow/open-traffic-generator-flow.yang
  - models-yang/models/discovery/open-traffic-generator-discovery.yang
  - models-yang/models/interface/open-traffic-generator-port.yang
  - models-yang/models/bgp/open-traffic-generator-bgp.yang
  - models-yang/models/lag/open-traffic-generator-lag.yang
  - models-yang/models/lacp/open-traffic-generator-lacp.yang

Imported modules were sourced from:
  - models-yang/models/...
*/
package lag

import (
	"github.com/openconfig/ygot/ygot"
)

// LagPath represents the /open-traffic-generator-lag/lags/lag YANG schema element.
type LagPath struct {
	*ygot.NodePath
}

// LagPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag YANG schema element.
type LagPathAny struct {
	*ygot.NodePath
}

// Lag_InRatePath represents the /open-traffic-generator-lag/lags/lag/state/in-rate YANG schema element.
type Lag_InRatePath struct {
	*ygot.NodePath
}

// Lag_InRatePathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/in-rate YANG schema element.
type Lag_InRatePathAny struct {
	*ygot.NodePath
}

// Lag_NamePath represents the /open-traffic-generator-lag/lags/lag/state/name YANG schema element.
type Lag_NamePath struct {
	*ygot.NodePath
}

// Lag_NamePathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/name YANG schema element.
type Lag_NamePathAny struct {
	*ygot.NodePath
}

// Lag_OperStatusPath represents the /open-traffic-generator-lag/lags/lag/state/oper-status YANG schema element.
type Lag_OperStatusPath struct {
	*ygot.NodePath
}

// Lag_OperStatusPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/oper-status YANG schema element.
type Lag_OperStatusPathAny struct {
	*ygot.NodePath
}

// Lag_OutRatePath represents the /open-traffic-generator-lag/lags/lag/state/out-rate YANG schema element.
type Lag_OutRatePath struct {
	*ygot.NodePath
}

// Lag_OutRatePathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/out-rate YANG schema element.
type Lag_OutRatePathAny struct {
	*ygot.NodePath
}

// Counters (container): Counters of an OTG LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/counters"
// Path from root: "/lags/lag/state/counters"
func (n *LagPath) Counters() *Lag_CountersPath {
	return &Lag_CountersPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "counters"},
			map[string]interface{}{},
			n,
		),
	}
}

// Counters (container): Counters of an OTG LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/counters"
// Path from root: "/lags/lag/state/counters"
func (n *LagPathAny) Counters() *Lag_CountersPathAny {
	return &Lag_CountersPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "counters"},
			map[string]interface{}{},
			n,
		),
	}
}

// InRate (leaf): The current receive rate of an OTG LAG, measured in
// bits per second.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/in-rate"
// Path from root: "/lags/lag/state/in-rate"
func (n *LagPath) InRate() *Lag_InRatePath {
	return &Lag_InRatePath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "in-rate"},
			map[string]interface{}{},
			n,
		),
	}
}

// InRate (leaf): The current receive rate of an OTG LAG, measured in
// bits per second.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/in-rate"
// Path from root: "/lags/lag/state/in-rate"
func (n *LagPathAny) InRate() *Lag_InRatePathAny {
	return &Lag_InRatePathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "in-rate"},
			map[string]interface{}{},
			n,
		),
	}
}

// Name (leaf): An arbitary name of an OTG LAG determined by the OTG
// configuration.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/name"
// Path from root: "/lags/lag/state/name"
func (n *LagPath) Name() *Lag_NamePath {
	return &Lag_NamePath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "name"},
			map[string]interface{}{},
			n,
		),
	}
}

// Name (leaf): An arbitary name of an OTG LAG determined by the OTG
// configuration.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/name"
// Path from root: "/lags/lag/state/name"
func (n *LagPathAny) Name() *Lag_NamePathAny {
	return &Lag_NamePathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "name"},
			map[string]interface{}{},
			n,
		),
	}
}

// OperStatus (leaf): The current operational state of an OTG LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/oper-status"
// Path from root: "/lags/lag/state/oper-status"
func (n *LagPath) OperStatus() *Lag_OperStatusPath {
	return &Lag_OperStatusPath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "oper-status"},
			map[string]interface{}{},
			n,
		),
	}
}

// OperStatus (leaf): The current operational state of an OTG LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/oper-status"
// Path from root: "/lags/lag/state/oper-status"
func (n *LagPathAny) OperStatus() *Lag_OperStatusPathAny {
	return &Lag_OperStatusPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "oper-status"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutRate (leaf): The current transmit rate of an OTG LAG, measured in
// bits per second.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/out-rate"
// Path from root: "/lags/lag/state/out-rate"
func (n *LagPath) OutRate() *Lag_OutRatePath {
	return &Lag_OutRatePath{
		NodePath: ygot.NewNodePath(
			[]string{"state", "out-rate"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutRate (leaf): The current transmit rate of an OTG LAG, measured in
// bits per second.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "state/out-rate"
// Path from root: "/lags/lag/state/out-rate"
func (n *LagPathAny) OutRate() *Lag_OutRatePathAny {
	return &Lag_OutRatePathAny{
		NodePath: ygot.NewNodePath(
			[]string{"state", "out-rate"},
			map[string]interface{}{},
			n,
		),
	}
}

// Lag_CountersPath represents the /open-traffic-generator-lag/lags/lag/state/counters YANG schema element.
type Lag_CountersPath struct {
	*ygot.NodePath
}

// Lag_CountersPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters YANG schema element.
type Lag_CountersPathAny struct {
	*ygot.NodePath
}

// Lag_Counters_InFramesPath represents the /open-traffic-generator-lag/lags/lag/state/counters/in-frames YANG schema element.
type Lag_Counters_InFramesPath struct {
	*ygot.NodePath
}

// Lag_Counters_InFramesPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters/in-frames YANG schema element.
type Lag_Counters_InFramesPathAny struct {
	*ygot.NodePath
}

// Lag_Counters_InOctetsPath represents the /open-traffic-generator-lag/lags/lag/state/counters/in-octets YANG schema element.
type Lag_Counters_InOctetsPath struct {
	*ygot.NodePath
}

// Lag_Counters_InOctetsPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters/in-octets YANG schema element.
type Lag_Counters_InOctetsPathAny struct {
	*ygot.NodePath
}

// Lag_Counters_MemberPortsUpPath represents the /open-traffic-generator-lag/lags/lag/state/counters/member-ports-up YANG schema element.
type Lag_Counters_MemberPortsUpPath struct {
	*ygot.NodePath
}

// Lag_Counters_MemberPortsUpPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters/member-ports-up YANG schema element.
type Lag_Counters_MemberPortsUpPathAny struct {
	*ygot.NodePath
}

// Lag_Counters_OutFramesPath represents the /open-traffic-generator-lag/lags/lag/state/counters/out-frames YANG schema element.
type Lag_Counters_OutFramesPath struct {
	*ygot.NodePath
}

// Lag_Counters_OutFramesPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters/out-frames YANG schema element.
type Lag_Counters_OutFramesPathAny struct {
	*ygot.NodePath
}

// Lag_Counters_OutOctetsPath represents the /open-traffic-generator-lag/lags/lag/state/counters/out-octets YANG schema element.
type Lag_Counters_OutOctetsPath struct {
	*ygot.NodePath
}

// Lag_Counters_OutOctetsPathAny represents the wildcard version of the /open-traffic-generator-lag/lags/lag/state/counters/out-octets YANG schema element.
type Lag_Counters_OutOctetsPathAny struct {
	*ygot.NodePath
}

// InFrames (leaf): The total number of packets received on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "in-frames"
// Path from root: "/lags/lag/state/counters/in-frames"
func (n *Lag_CountersPath) InFrames() *Lag_Counters_InFramesPath {
	return &Lag_Counters_InFramesPath{
		NodePath: ygot.NewNodePath(
			[]string{"in-frames"},
			map[string]interface{}{},
			n,
		),
	}
}

// InFrames (leaf): The total number of packets received on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "in-frames"
// Path from root: "/lags/lag/state/counters/in-frames"
func (n *Lag_CountersPathAny) InFrames() *Lag_Counters_InFramesPathAny {
	return &Lag_Counters_InFramesPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"in-frames"},
			map[string]interface{}{},
			n,
		),
	}
}

// InOctets (leaf): The total number of octets received on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "in-octets"
// Path from root: "/lags/lag/state/counters/in-octets"
func (n *Lag_CountersPath) InOctets() *Lag_Counters_InOctetsPath {
	return &Lag_Counters_InOctetsPath{
		NodePath: ygot.NewNodePath(
			[]string{"in-octets"},
			map[string]interface{}{},
			n,
		),
	}
}

// InOctets (leaf): The total number of octets received on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "in-octets"
// Path from root: "/lags/lag/state/counters/in-octets"
func (n *Lag_CountersPathAny) InOctets() *Lag_Counters_InOctetsPathAny {
	return &Lag_Counters_InOctetsPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"in-octets"},
			map[string]interface{}{},
			n,
		),
	}
}

// MemberPortsUp (leaf): The current *-number of member ports on the LAG in UP state.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "member-ports-up"
// Path from root: "/lags/lag/state/counters/member-ports-up"
func (n *Lag_CountersPath) MemberPortsUp() *Lag_Counters_MemberPortsUpPath {
	return &Lag_Counters_MemberPortsUpPath{
		NodePath: ygot.NewNodePath(
			[]string{"member-ports-up"},
			map[string]interface{}{},
			n,
		),
	}
}

// MemberPortsUp (leaf): The current *-number of member ports on the LAG in UP state.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "member-ports-up"
// Path from root: "/lags/lag/state/counters/member-ports-up"
func (n *Lag_CountersPathAny) MemberPortsUp() *Lag_Counters_MemberPortsUpPathAny {
	return &Lag_Counters_MemberPortsUpPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"member-ports-up"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutFrames (leaf): The total number of packets transmitted on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "out-frames"
// Path from root: "/lags/lag/state/counters/out-frames"
func (n *Lag_CountersPath) OutFrames() *Lag_Counters_OutFramesPath {
	return &Lag_Counters_OutFramesPath{
		NodePath: ygot.NewNodePath(
			[]string{"out-frames"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutFrames (leaf): The total number of packets transmitted on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "out-frames"
// Path from root: "/lags/lag/state/counters/out-frames"
func (n *Lag_CountersPathAny) OutFrames() *Lag_Counters_OutFramesPathAny {
	return &Lag_Counters_OutFramesPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"out-frames"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutOctets (leaf): The total number of octets transmitted on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "out-octets"
// Path from root: "/lags/lag/state/counters/out-octets"
func (n *Lag_CountersPath) OutOctets() *Lag_Counters_OutOctetsPath {
	return &Lag_Counters_OutOctetsPath{
		NodePath: ygot.NewNodePath(
			[]string{"out-octets"},
			map[string]interface{}{},
			n,
		),
	}
}

// OutOctets (leaf): The total number of octets transmitted on the LAG.
// ----------------------------------------
// Defining module: "open-traffic-generator-lag"
// Instantiating module: "open-traffic-generator-lag"
// Path from parent: "out-octets"
// Path from root: "/lags/lag/state/counters/out-octets"
func (n *Lag_CountersPathAny) OutOctets() *Lag_Counters_OutOctetsPathAny {
	return &Lag_Counters_OutOctetsPathAny{
		NodePath: ygot.NewNodePath(
			[]string{"out-octets"},
			map[string]interface{}{},
			n,
		),
	}
}
